INSERT INTO USRIND.OTC_T_PARAM_JOB_URM_desa (NOMBRE_JOB_CM,SHELL_URM,PARAMETROS,FORMATO_PARAMETROS,VR_PARAMETRO_FECHA,ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,OBSERVACION,FECHA_PROCESO,PERIODICIDAD)
SELECT
'D_URMCBMBILL4060',
'/home/nae108834/cp_terminales_simcards/bin/OTC_T_R_CBM_BILL.sh',
PARAMETROS,FORMATO_PARAMETROS,
'SYSDATE',
ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,
'Shell que inserta datos de oracle hacia hive',
FECHA_PROCESO, PERIODICIDAD
FROM USRIND.OTC_T_PARAM_JOB_URM
WHERE NOMBRE_JOB_CM='URMMOHAST1800';
COMMIT;


--D_pro_urm_TBL
--------------------------------



INSERT INTO USRIND.OTC_T_PARAM_JOB_URM (NOMBRE_JOB_CM,SHELL_URM,PARAMETROS,FORMATO_PARAMETROS,VR_PARAMETRO_FECHA,ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,OBSERVACION,FECHA_PROCESO,PERIODICIDAD)
SELECT
'URMTRMNLSVUSR4050',
'/RAW/RDB/OTC_T_V_USUARIOS/bin/OTC_T_V_USUARIOS.sh',
PARAMETROS,FORMATO_PARAMETROS,
'SYSDATE',
ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,
'Shell que inserta datos de oracle hacia hive',
FECHA_PROCESO, PERIODICIDAD
FROM USRIND.OTC_T_PARAM_JOB_URM_DESA
WHERE NOMBRE_JOB_CM='D_URMTRMNLSVUSR4050';
COMMIT;



INSERT INTO USRIND.OTC_T_PARAM_JOB_URM (NOMBRE_JOB_CM,SHELL_URM,PARAMETROS,FORMATO_PARAMETROS,VR_PARAMETRO_FECHA,ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,OBSERVACION,FECHA_PROCESO,PERIODICIDAD)
SELECT
'URMCBMBILL4060',
'/RAW/RDB/OTC_T_R_CBM_BILL/bin/OTC_T_R_CBM_BILL.sh',
PARAMETROS,FORMATO_PARAMETROS,
'SYSDATE',
ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,
'Shell que inserta datos de oracle hacia hive',
FECHA_PROCESO, PERIODICIDAD
FROM USRIND.OTC_T_PARAM_JOB_URM_DESA
WHERE NOMBRE_JOB_CM='D_URMCBMBILL4060';
COMMIT;

