INSERT INTO USRIND.OTC_T_PARAM_JOB_URM_desa (NOMBRE_JOB_CM,SHELL_URM,PARAMETROS,FORMATO_PARAMETROS,VR_PARAMETRO_FECHA,ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,OBSERVACION,FECHA_PROCESO,PERIODICIDAD)
SELECT
'D_URMCBMBILL4060',
'/home/nae108834/cp_terminales_simcards/bin/OTC_T_R_CBM_BILL.sh',
PARAMETROS,FORMATO_PARAMETROS,
'SYSDATE',
ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,
'Shell que inserta datos de oracle hacia hive.',
FECHA_PROCESO, PERIODICIDAD
FROM USRIND.OTC_T_PARAM_JOB_URM
WHERE NOMBRE_JOB_CM='URMMOHAST1800';
COMMIT;


INSERT INTO USRIND.OTC_T_PARAM_JOB_URM (NOMBRE_JOB_CM,SHELL_URM,PARAMETROS,FORMATO_PARAMETROS,VR_PARAMETRO_FECHA,ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,OBSERVACION,FECHA_PROCESO,PERIODICIDAD)
SELECT
'URMCTLGFDLPLNSXCL1390',
'/RAW/ARCHIVOS/OTC_T_CTL_FDL_PLANES_EXCL/bin/OTC_T_CTL_FDL_PLANES_EXCL.sh',
PARAMETROS,FORMATO_PARAMETROS,
'00000000',
ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,
'Shell que inserta datos del catalogo Planes Excluir hacia hive.',
FECHA_PROCESO, PERIODICIDAD
FROM USRIND.OTC_T_PARAM_JOB_URM_DESA
WHERE NOMBRE_JOB_CM='D_URMCTLGFDLPLNSXCL1390';
COMMIT;


--------------------------------



INSERT INTO USRIND.OTC_T_PARAM_JOB_URM_desa (NOMBRE_JOB_CM,SHELL_URM,PARAMETROS,FORMATO_PARAMETROS,VR_PARAMETRO_FECHA,ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,OBSERVACION,FECHA_PROCESO,PERIODICIDAD)
SELECT
'D_URMTRFLMNTDSCNT3090',
'/home/nae106995/RAW/RBM/OTC_T_TARIFFELEMENTDISCOUNT/bin/OTC_T_TARIFFELEMENTDISCOUNT.sh',
PARAMETROS,FORMATO_PARAMETROS,
'SYSDATE',
ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,
'Shell que inserta datos de oracle hacia hive.',
FECHA_PROCESO, PERIODICIDAD
FROM USRIND.OTC_T_PARAM_JOB_URM
WHERE NOMBRE_JOB_CM='URMMOHAST1800';
COMMIT;


INSERT INTO USRIND.OTC_T_PARAM_JOB_URM (NOMBRE_JOB_CM,SHELL_URM,PARAMETROS,FORMATO_PARAMETROS,VR_PARAMETRO_FECHA,ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,OBSERVACION,FECHA_PROCESO,PERIODICIDAD)
SELECT
'URMCTLGFDLPLNSXCL1390',
'/RAW/ARCHIVOS/OTC_T_CTL_FDL_PLANES_EXCL/bin/OTC_T_CTL_FDL_PLANES_EXCL.sh',
PARAMETROS,FORMATO_PARAMETROS,
'00000000',
ETAPA,VR_OTROS_PARAMETROS,FECHA_INI,PERIODO_EJEC_RETRO,
'Shell que inserta datos del catalogo Planes Excluir hacia hive.',
FECHA_PROCESO, PERIODICIDAD
FROM USRIND.OTC_T_PARAM_JOB_URM_DESA
WHERE NOMBRE_JOB_CM='D_URMCTLGFDLPLNSXCL1390';
COMMIT;

--D_pro_urm_TBL


