
--PARAMETROS PARA LA ENTIDAD EXTRCTRTRMNLS0080
DELETE FROM params_des WHERE ENTIDAD='EXTRCTRTRMNLS0080';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','HIVEDB','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_MASTER','yarn','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_DRIVER_MEMORY','16G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_EXECUTOR_MEMORY','16G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_EXECUTOR_CORES','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_NUM_EXECUTORS','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','PARAM1_FECHA','date_format(sysdate(),''%Y%m%d'')','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_RUTA','/home/nae108834/cp_terminales_simcards','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','ETAPA','1','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','SHELL','/home/nae108834/cp_terminales_simcards/bin/OTC_T_EXT_TERMINALES.sh','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_BASE_DATOS','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_FTP_PUERTO_OUT','22','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_FTP_USER_OUT','telefonicaecuadordev','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_FTP_HOSTNAME_OUT','ftp.cloud.varicent.com','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_FTP_PASS_OUT','kwXugTotN8oIrBmy1lJF','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_FTP_RUTA_OUT','/Data','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_NOM_ARCHIVO','Extractor_Terminales.txt','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_TIPO_CARGA','overwrite','0','1');
SELECT * FROM params_des WHERE ENTIDAD='EXTRCTRTRMNLS0080';

--PARAMETROS PARA LA ENTIDAD OTC_T_AJUSTES_TERMINALES
DELETE FROM params_des WHERE entidad='OTC_T_AJUSTES_TERMINALES';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','ETAPA','1',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_RUTA','/home/nae108834/cp_terminales_simcards',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_RUTA','"/FACTURACION_TERMINALES"',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_USER','NABIFI01',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_PUERTO','9694',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_HOSTNAME','fileuio03',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_PASS','bii2022-NA10',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_NOM_ARCHIVO','AJUSTES_TERMINALES.xlsx',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_DIR_HDFS_CAT','db_desarrollo2021.tmp_ajsts_terminales',1,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vMASTER','yarn','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vDRIVER_MEMORY','4G','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vEXECUTOR_MEMORY','4G','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vNUM_EXECUTORS','4','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vNUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params_des WHERE ENTIDAD='OTC_T_AJUSTES_TERMINALES';





