--PARAMETROS PARA LA ENTIDAD SHTRMNLSMCRDS0010
DELETE FROM params WHERE ENTIDAD='SHTRMNLSMCRDS0010';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_EXECUTOR_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','PARAM1_FECHA','date_format(sysdate(),''%Y%m%d'')','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_RUTA','/RGenerator/cp_terminales_simcards','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','SHELL','/RGenerator/cp_terminales_simcards/bin/SH_TERMINALES_SIMCARDS.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_PUERTO1','9559','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_PUERTO2','9557','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_USER','ftp_contabilidad','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_HOSTNAME','10.112.47.36','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_PASS','Telefonica.2018&','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_RUTA','/','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_0','LISTADO_RUC_DAS_RETAIL.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_1','CONCEPTOS_FACT_ADICIONALES.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_2','"100*Nueva*Categoria*-*2022.xlsx"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_3','"ASIGNACION*CANAL*DE*VENTAS*v3.xlsx"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_4','CTL_CAT_SEG_SUB_SEG.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO2_0','USUARIOS_CANAL_ONLINE.xlsx','0','1');

INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO2_1','TIPO_CANAL.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO_MP','Catalogo_Segmento_Terminales.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_BASE_DATOS','db_cs_terminales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_TC','otc_t_catalogo_tipo_canal','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_CANAL','otc_t_asigna_canal_ventas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_SEG','otc_t_ctl_cat_seg_sub_seg','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_CST','otc_t_ctl_seg_terminal','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_RDR','otc_t_catalogo_ruc_das_retail','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_T','otc_t_catalogo_terminales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_UO','otc_t_catalogo_canal_online','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_ZTFI','OTC_T_CONCEPTOS_FACT_ADICION','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_USUARIO_BACKOFF','"NAG00029","NAINJA02","NALAJA01","NAUIJA61","NAUIJA62","NAUIJA65","NAUIJA66","NAUIJA67","NAUIJA82","internal"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_USUARIO4','"NA002828"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_USUARIO_FINAL','"NA400413","NA002132","NA1000206","NA002152","MFSALAZAR","NA400406","NA002420"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MESES','2','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MESES1','6','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MESES2','18','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_PUERTO_OUT','22','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_USER_OUT','telefonicaecuadorprod','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_HOSTNAME_OUT','ftp.cloud.varicent.com','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_PASS_OUT','RqiZ2lkJmeiQTi2hvRwd','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_FTP_RUTA_OUT','/Data','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO','Extractor_Terminales.txt','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TIPO_CARGA','overwrite','0','1');
SELECT * FROM params WHERE ENTIDAD='SHTRMNLSMCRDS0010';

--PARAMETROS PARA LA ENTIDAD OTC_T_AJUSTES_TERMINALES
DELETE FROM params WHERE entidad='OTC_T_AJUSTES_TERMINALES';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_RUTA','"/FACTURACION_TERMINALES"',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_USER','NABIFI01',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_PUERTO','9694',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_HOSTNAME','fileuio03',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_PASS','bii2022-NA10',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_FTP_NOM_ARCHIVO','AJUSTES_TERMINALES.xlsx',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','VAL_DIR_HDFS_CAT','db_temporales.tmp_ajsts_terminales',1,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vMASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vDRIVER_MEMORY','4G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vEXECUTOR_MEMORY','4G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vNUM_EXECUTORS','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_TERMINALES','vNUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='OTC_T_AJUSTES_TERMINALES';

--PARAMETROS PARA LA ENTIDAD OTC_T_R_AM_CPE
DELETE FROM params WHERE entidad='OTC_T_R_AM_CPE';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','TDTABLE','r_am_cpe',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','HIVEDB','db_desarrollo2021',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_R_AM_CPE','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='OTC_T_R_AM_CPE';

--PARAMETROS PARA LA ENTIDAD URMRCBMBILL3100
DELETE FROM params WHERE entidad='URMRCBMBILL3100';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','TDTABLE','r_cbm_bill',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','HIVEDB','db_desarrollo2021',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMRCBMBILL3100','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='URMRCBMBILL3100';

--PARAMETROS PARA LA ENTIDAD URMTRMNLSVUSR3090
DELETE FROM params WHERE entidad='URMTRMNLSVUSR3090';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','VAL_RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','TDTABLE','otc_v_usuarios',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','HIVEDB','db_desarrollo2021',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR3090','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='URMTRMNLSVUSR3090';

--PARAMETROS PARA LA ENTIDAD URMTRMNLSFCT3100
DELETE FROM params WHERE entidad='URMTRMNLSFCT3100';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','VAL_RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','TDTABLE','otc_t_terminales_fact',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','HIVEDB','db_desarrollo2021',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSFCT3100','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='URMTRMNLSFCT3100';

--PARAMETROS PARA LA ENTIDAD URMTRMNLSNC3090
DELETE FROM params WHERE entidad='URMTRMNLSNC3090';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','VAL_RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','TDTABLE','otc_t_terminales_nc',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','HIVEDB','db_desarrollo2021',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','VAL_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','VAL_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','VAL_NUM_EXECUTORS','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSNC3090','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='URMTRMNLSNC3090';



--AGREGA NUEVOS CAMPOS A TABLA DESTINO otc_t_terminales_simcards
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (forma_pago_factura varchar(40) COMMENT 'forma de pago para facturas');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tarjeta_banco varchar(40) COMMENT 'tarjeta de banco');  
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (cuotas string varchar(3) 'cuotas del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tarjeta_banco2 varchar(40) COMMENT 'tarjeta de banco2');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (cuotas2 varchar(3) COMMENT 'cuotas2 del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tarjeta_banco3 varchar(40) COMMENT 'tarjeta de banco3');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (cuotas3 varchar(3) COMMENT 'cuotas3 del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (segmento_final string COMMENT 'segmento final');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_canal string COMMENT 'identificador del canal');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_sub_canal string COMMENT 'identificador del sub canal');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_tipo_movimiento string COMMENT 'identificador del tipo de movimiento');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_producto string COMMENT 'identificador del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tipo_movimiento_mes string COMMENT 'tipo de movimiento en el mes');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (fecha_alta timestamp COMMENT 'fecha de alta');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (antiguedad_meses double COMMENT 'antiguedad en meses');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_hash string COMMENT 'id hash del registro conformado por el telefono, cuenta y fecha proceso');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (ruc_distribuidor string COMMENT 'identificador del distribuidor');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (codigo_plaza string COMMENT 'codigo de la plaza');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (nom_plaza string COMMENT 'nombre de la plaza');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (ciudad string COMMENT 'ciudad');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (provincia string COMMENT 'provincia');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (nuevo_subcanal string COMMENT 'nuevo sub canal');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tipo_doc_cliente string COMMENT 'tipo de documento del cliente');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (linea_negocio_homologado string COMMENT 'linea de negocio homologada');

