
--PARAMETROS PARA LA ENTIDAD EXTRCTRTRMNLS0080
DELETE FROM params_des WHERE ENTIDAD='EXTRCTRTRMNLS0080';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','HIVEDB','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_MASTER','yarn','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_DRIVER_MEMORY','16G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_EXECUTOR_MEMORY','16G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_EXECUTOR_CORES','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_NUM_EXECUTORS','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','PARAM1_FECHA','date_format(sysdate(),''%Y%m%d'')','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_RUTA','/home/nae108834/cp_terminales_simcards','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','ETAPA','1','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','SHELL','/home/nae108834/cp_terminales_simcards/bin/OTC_T_EXT_TERMINALES.sh','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_BASE_DATOS','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_SFTP_PUERTO_OUT','22','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_SFTP_USER_OUT','telefonicaecuadorprod','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_SFTP_HOSTNAME_OUT','ftp.cloud.varicent.com','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_SFTP_PASS_OUT','RqiZ2lkJmeiQTi2hvRwd','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_SFTP_RUTA_OUT','/Data','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_NOM_ARCHIVO','Extractor_Terminales.txt','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_DIR_HDFS_CAT','db_desarrollo2021.tmp_ajsts_terminales',1,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_SFTP_RUTA','"COMISIONES/Indirectos/Multipais/PROYECTO_COMISIONES/FACTURACION_TERMINALES"',0,1);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0080','VAL_SFTP_NOM_ARCHIVO','AJUSTES_TERMINALES.xlsx',0,1);
SELECT * FROM params_des WHERE ENTIDAD='EXTRCTRTRMNLS0080';

