
--PARAMETROS PARA LA ENTIDAD SHTRMNLSMCRDS0010
DELETE FROM params WHERE ENTIDAD='SHTRMNLSMCRDS0010';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_DRIVER_MEMORY','24G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_EXECUTOR_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','PARAM1_FECHA','date_format(sysdate(),''%Y%m%d'')','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_RUTA','/RGenerator/cp_terminales_simcards','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','SHELL','/RGenerator/cp_terminales_simcards/bin/SH_TERMINALES_SIMCARDS.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_0','LISTADO_RUC_DAS_RETAIL.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_1','CONCEPTOS_FACT_ADICIONALES.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_2','"100*Nueva*Categoria*-*2022.xlsx"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_3','"ASIGNACION*CANAL*DE*VENTAS*v3.xlsx"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO1_4','CTL_CAT_SEG_SUB_SEG.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO2_0','USUARIOS_CANAL_ONLINE.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_SFTP_RUTA_1','''"/Inteligencia~}<de~}<Mercado/07_Analisis_epc-rlf/02_Análisis/Terminales/Catalogos"''','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_SFTP_RUTA_2','''"/Business~}<Intelligence/3_Operaciones/Procesos/EMERGENTE/NC/PARQUE/CATALOGO"''','0','1');

INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO2_1','TIPO_CANAL.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_NOM_ARCHIVO_MP','Catalogo_Segmento_Terminales.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_BASE_DATOS','db_cs_terminales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_TC','otc_t_catalogo_tipo_canal','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_CANAL','otc_t_asigna_canal_ventas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_SEG','otc_t_ctl_cat_seg_sub_seg','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_CST','otc_t_ctl_seg_terminal','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_RDR','otc_t_catalogo_ruc_das_retail','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_T','otc_t_catalogo_terminales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TABLA_UO','otc_t_catalogo_canal_online','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_USUARIO_BACKOFF','"NAG00029","NAINJA02","NALAJA01","NAUIJA61","NAUIJA62","NAUIJA65","NAUIJA66","NAUIJA67","NAUIJA82","internal"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_USUARIO4','"NA002828"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_USUARIO_FINAL','"NA400413","NA002132","NA1000206","NA002152","MFSALAZAR","NA400406","NA002420"','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MESES','2','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MESES1','6','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_MESES2','18','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('SHTRMNLSMCRDS0010','VAL_TIPO_CARGA','overwrite','0','1');
SELECT * FROM params WHERE ENTIDAD='SHTRMNLSMCRDS0010';

--PARAMETROS PARA LA ENTIDAD URMCBMBILL4060
DELETE FROM params WHERE entidad='URMCBMBILL4060';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','RUTA','/RAW/RDB/OTC_T_R_CBM_BILL',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','SHELL','/RAW/RDB/OTC_T_R_CBM_BILL/bin/OTC_T_R_CBM_BILL.sh',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','TDTABLE','r_cbm_bill',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','HIVEDB','db_rdb',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMCBMBILL4060','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='URMCBMBILL4060';

--PARAMETROS PARA LA ENTIDAD URMTRMNLSVUSR4050
DELETE FROM params WHERE entidad='URMTRMNLSVUSR4050';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','VAL_RUTA','/RAW/RDB/OTC_T_V_USUARIOS',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','SHELL','/RAW/RDB/OTC_T_V_USUARIOS/bin/OTC_T_V_USUARIOS.sh',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','TDTABLE','otc_v_usuarios',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','HIVEDB','db_rdb',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRMNLSVUSR4050','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='URMTRMNLSVUSR4050';

--PARAMETROS PARA LA ENTIDAD TRMNLSFCT0040
DELETE FROM params WHERE entidad='TRMNLSFCT0040';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','VAL_RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','SHELL','/RGenerator/cp_terminales_simcards/bin/OTC_T_TERMINALES_FACT.sh',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','TDTABLE','otc_t_terminales_fact',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','HIVEDB','db_rbm',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSFCT0040','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='TRMNLSFCT0040';

--PARAMETROS PARA LA ENTIDAD TRMNLSNC0030
DELETE FROM params WHERE entidad='TRMNLSNC0030';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','VAL_RUTA','/RGenerator/cp_terminales_simcards',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','SHELL','/RGenerator/cp_terminales_simcards/bin/OTC_T_TERMINALES_NC.sh',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','TDTABLE','otc_t_terminales_nc',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','HIVEDB','db_rbm',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','VAL_TIPO_CARGA','overwrite',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','VAL_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','VAL_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','VAL_NUM_EXECUTORS','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('TRMNLSNC0030','VAL_NUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='TRMNLSNC0030';


--PARAMETROS PARA LA ENTIDAD EXTRCTRTRMNLS0070
DELETE FROM params WHERE ENTIDAD='EXTRCTRTRMNLS0070';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_EXECUTOR_CORES','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','PARAM1_FECHA','date_format(sysdate(),''%Y%m%d'')','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_RUTA','/RGenerator/reportes/Ext_Terminales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','SHELL','/RGenerator/reportes/Ext_Terminales/bin/OTC_T_EXT_TERMINALES.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_BASE_DATOS','db_cs_terminales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_SFTP_PUERTO_OUT','22','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_SFTP_USER_OUT','telefonicaecuadorprod','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_SFTP_HOSTNAME_OUT','ftp.cloud.varicent.com','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_SFTP_PASS_OUT','RqiZ2lkJmeiQTi2hvRwd','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_SFTP_RUTA_OUT','/Data','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_NOM_ARCHIVO','Extractor_Terminales.txt','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_DIR_HDFS_CAT','db_temporales.tmp_ajsts_terminales',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_SFTP_RUTA','"COMISIONES/Indirectos/Multipais/PROYECTO_COMISIONES/FACTURACION_TERMINALES"',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCTRTRMNLS0070','VAL_SFTP_NOM_ARCHIVO','AJUSTES_TERMINALES.xlsx',0,1);
SELECT * FROM params WHERE ENTIDAD='EXTRCTRTRMNLS0070';




--AGREGA NUEVOS CAMPOS A TABLA DESTINO otc_t_terminales_simcards
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (forma_pago_factura varchar(40) COMMENT 'forma de pago para facturas');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tarjeta_banco varchar(40) COMMENT 'tarjeta de banco');  
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (cuotas string varchar(3) 'cuotas del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tarjeta_banco2 varchar(40) COMMENT 'tarjeta de banco2');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (cuotas2 varchar(3) COMMENT 'cuotas2 del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tarjeta_banco3 varchar(40) COMMENT 'tarjeta de banco3');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (cuotas3 varchar(3) COMMENT 'cuotas3 del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (segmento_final string COMMENT 'segmento final');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_canal string COMMENT 'identificador del canal');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_sub_canal string COMMENT 'identificador del sub canal');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_tipo_movimiento string COMMENT 'identificador del tipo de movimiento');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_producto string COMMENT 'identificador del producto');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tipo_movimiento_mes string COMMENT 'tipo de movimiento en el mes');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (fecha_alta timestamp COMMENT 'fecha de alta');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (antiguedad_meses double COMMENT 'antiguedad en meses');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (id_hash string COMMENT 'id hash del registro conformado por el telefono, cuenta y fecha proceso');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (ruc_distribuidor string COMMENT 'identificador del distribuidor');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (codigo_plaza string COMMENT 'codigo de la plaza');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (nom_plaza string COMMENT 'nombre de la plaza');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (ciudad string COMMENT 'ciudad');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (provincia string COMMENT 'provincia');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (nuevo_subcanal string COMMENT 'nuevo sub canal');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (tipo_doc_cliente string COMMENT 'tipo de documento del cliente');
ALTER TABLE db_cs_terminales.otc_t_terminales_simcards ADD COLUMNS (linea_negocio_homologado string COMMENT 'linea de negocio homologada');

